config/routes.rb
Caninae::Application.routes.draw do
  resources :people
  resources :animal_kennels
  resources :animal_owners
  resources :succeeds
  resources :preceeds
  resources :dominates
  resources :titles
  resources :achievements
  resources :certifications
  resources :offspring_litters
  resources :litters
  resources :kennel_litters
  resources :person_kennels
  resources :kennels
  resources :registrations
  resources :animal_breeders
  resources :clearances
  resources :animals
  resources :events
  resources :locations

  namespace :tollerdata do
    get '/', :to => 'home#show'

    get :home, to:'home#show'
    get :about, to:'home#about'

    resources :animals do
      resources :siblings
      resources :offspring
      resources :pedigree do
        get :hip, to:'pedigree#hip'
        get :longevity, to:'pedigree#longevity'
      end
      resource :image
      resource :health do
        resources :categories, to:"health/categories"
      end
    end

    get :default, to:'home#show'
    resource :verify
  end
end

app/models/tollerdata.rb
module Tollerdata
  def self.table_name_prefix
    'tollerdata_'
  end
end

app/models/tollerdata/animal.rb
class Tollerdata::Animal < ::Animal
  # attr_accessible :title, :body
end

app/models/tollerdata/health.rb
module Tollerdata::Health
  def self.table_name_prefix
    'tollerdata_health_'
  end
end

app/models/tollerdata/health/category.rb
class Tollerdata::Health::Category < ActiveRecord::Base
  attr_accessible :name

  def self.general_background
    self.find_by_name "General Background"
  end

end

app/models/tollerdata/search.rb
class Tollerdata::Search
  extend ActiveModel::Naming
  include ActiveModel::Conversion
  include ActiveModel::MassAssignmentSecurity

  def persisted?; false; end

  attr_accessible :query
  attr_accessor :query

end

app/controllers/tollerdata/animals_controller.rb
class Tollerdata::AnimalsController < Tollerdata::TollerdataController
  def index
    if params[:query]
      q = "%#{params[:query]}%"
      @animals =
        Animal.where("name like ? or call_name like ? collate nocase", q, q)
    else 
      @animals = Animal.limit(10)
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @animals }
    end
  end

  def show
    @animal = Animal.find params[:id]
    @pedigree_click = :animal
    respond_to do |format|
      format.html
      format.json { render json:@animal }
    end
  end
end

app/controllers/tollerdata/health/categories_controller.rb
class Tollerdata::Health::CategoriesController < Tollerdata::TollerdataController

  def show
    render("tollerdata/healths/show", locals:{
             animal:Animal.find(params[:animal_id]),
             category:Tollerdata::Health::Category.find(params[:id])})
  end

end

app/controllers/tollerdata/healths_controller.rb
class Tollerdata::HealthsController < Tollerdata::TollerdataController
  def show
    render "show", locals:{
      animal:Animal.find(params[:animal_id]),
      category:Tollerdata::Health::Category.general_background
    }
  end
end

app/controllers/tollerdata/home_controller.rb
class Tollerdata::HomeController < Tollerdata::TollerdataController
  def show
    @search = Tollerdata::Search.new
  end
end

app/controllers/tollerdata/offspring_controller.rb
class Tollerdata::OffspringController < Tollerdata::TollerdataController
  def index
    @animal = Animal.find params[:animal_id]
    where = nil
    if @animal.sex == "female"
      where = "animals.mother_id = #{@animal.id} and parent.id = animals.father_id"
    else
      where = "animals.father_id = #{@animal.id} and parent.id = animals.mother_id"
    end
    @offspring =
      Animal.
      joins("join animals as parent").
      where(where).
      order("parent.name, animals.name")
  end
end

app/controllers/tollerdata/pedigree_controller.rb
class Tollerdata::PedigreeController < Tollerdata::TollerdataController

  def show
    @animal = Animal.find params[:animal_id]
    @generations = (params[:pedigree_id] || params[:id]).to_i
    @pedigree_click = :pedigree
    render :show
  end

  def hip
    @annotation = :hip
    show
  end

  def longevity
    @annotation = :longevity
    show
  end

end

app/controllers/tollerdata/searches_controller.rb
class Tollerdata::SearchesController < Tollerdata::TollerdataController
  def create
    render_animals_for params[tollerdata_verify]
  end
end

app/controllers/tollerdata/siblings_controller.rb
class Tollerdata::SiblingsController < Tollerdata::TollerdataController
  def index
    @animal = Animal.find params[:animal_id]
    where = ["id <> #{@animal.id}"]
    args = []
    if @animal.father
      where << "father_id = ?" 
      args << @animal.father.id
    end
    if @animal.mother
      where << "mother_id = ?" 
      args << @animal.mother.id
    end
    if where.empty?
      @siblings = []
    else
      @siblings = Animal.where(where.join(" and "), *args)
    end
  end
end

app/controllers/tollerdata/tollerdata_controller.rb
class Tollerdata::TollerdataController < ApplicationController
  layout 'tollerdata'
end

app/helpers/tollerdata/animals_helper.rb
module Tollerdata::AnimalsHelper

  def ofa
    false
  end

  def score condition, registry, value
    case [condition, registry.downcase]
    when [:hip, "ofa"]
      if m = value.match(/^DTR-\d+([EGF])\d+[MF]-(T|PI|VPI|NOPI)$/)
        case m[1]
        when 'E'; "Excellent"
        when 'G'; "Good"
        when 'F'; "Fair"
        end
      else
        "nope"
      end
    else; nil
    end
  end

  def image json
    image = json["IMAGE"]
    image.blank? ? nil : image
  end

  def image_user json
    user = clean(json["IMAGEUSER"])
    user.blank? ? nil : user
  end

  def web_site json
    web_site = json["WEBSITE"]
    web_site.blank? ? nil : web_site
  end

  def clean string
    string = string.squish if string
    string.blank? ? nil : string
  end

  COUNTRIES = {
    "US" => "United States",
    "FI" => "Finland",
    "CA" => "Canada"
  }

  def country_name code
    code.upcase! if code
    COUNTRIES[code] || code
  end

  def country json
    country_name(clean json["COUNTRY"])
  end
  
  def name jsona
    clean json["NAME"]
  end
  
  def link_name json
    clean [prefix(json), json["NAME"], suffix(json)].join(" ")
  end
  
  def prefix json
    clean json["FRONTTITLES"]
  end
  
  def suffix json
    clean json["ENDTITLES"]
  end
  
  def color json
    clean json["COLOR"]
  end
  
  def registry json
    clean json["REGISTRY"]
  end

  def registration_number json
    clean json["REGISTRATIONNUMBER"]
  end
  
  def breeder json
    clean json["BREEDER"]
  end
  
  def owner json
    clean json["OWNER"]
  end
  
  def death_reason json
    clean json["DEATHREASON"]
  end

  def addl_death_reason json
    clean json["ADDLDEATHREASON"]
  end

  def pra_test json
    case clean(json["PRATEST"].downcase)
    when 'a'; "Clear"
    when 'b'; "Carrier"
    when 'c'; "Affected"
    end
  end

  def cea_test json
    case clean(json["CEATEST"].downcase)
    when 'a'; "Clear"
    when 'b'; "Carrier"
    when 'c'; "Affected"
    end
  end

  def combine json, a, b
    clean [clean(json[a]), clean(json[b])].compact.join(" ")
  end

  def hips json
    combine json, "HIPREGISTRY", "HIPID"
  end
  
  def eyes json
    combine json, "EYEREGISTRY", "EYEID"
  end
  
  def heart json
    combine json, "HEARTREGISTRY", "HEARTID"
  end
  
  def elbows json
    combine json, "ELBOWREGISTRY", "ELBOWID"
  end
  
  def thyroid json
    combine json, "THYROIDREGISTRY", "THYROIDID"
  end
  
  def longevity animal
    birth = animal.birth
    death = animal.death
    return nil if !death || !birth
    years = (death.to_epoch - birth.to_epoch)/(365*24*60.0*60.0)
    int = years.truncate
    years -= int
    if years > 2.0/3
      years = "#{int+1}"
    elsif years > 1.0/3
      years = "#{int}.5"
    else 
      years = int.to_s
    end
    "#{years} years"
  end

end

app/helpers/tollerdata/health/categories_helper.rb
module Tollerdata::Health::CategoriesHelper
end

app/helpers/tollerdata/healths_helper.rb
module Tollerdata::HealthsHelper
end

app/helpers/tollerdata/home_helper.rb
module Tollerdata::HomeHelper
end

app/helpers/tollerdata/offspring_helper.rb
module Tollerdata::OffspringHelper
end

app/helpers/tollerdata/pedigree_helper.rb
module Tollerdata::PedigreeHelper

  def pedigree_path animal, pedigree_click, generations
    case pedigree_click
    when :pedigree;  tollerdata_animal_pedigree_path(animal.id, generations )
    else; tollerdata_animal_path(animal)
    end
  end

end

app/views/tollerdata/pedigree/_new_pedigree.html.haml
- animals.each do |animal|
  %div.tr
    %div.td{style:"width:#{100*1/generations-5}%"}
      - if animal
        - json = MultiJson.load animal.import_json
        - if link
          = link_to link_name(json), pedigree_path(animal, @pedigree_click, @generations)
        - else
          = link_name(json)
        - if @annotation == :hip && hips(json)
          %font{color:"green"} [#{hips(json)}]
        - if @annotation == :longevity && longevity(animal)
          %font{color:"green"} [#{longevity(animal)}]
        - if generations > 1
          %div.td{style:"width:#{100*(1-1.0/generations)+5}%"}
            - ancestors = [animal.father, animal.mother]
            / = debug ancestors
            / = ancestors #{generations-1}
            = render partial:"tollerdata/pedigree/new_pedigree", locals:{animals:ancestors, |
                                                 generations:generations-1, |
                                                 link:true } |

app/views/tollerdata/pedigree/_pedigree.html.haml
%table{style:"width:100%"}
  %tbody
    - animals.each do |animal|
      %tr
        %td{style:"width:#{100*1/generations-5}%"}
          - if animal
            - json = MultiJson.load animal.import_json
            - if link
              = link_to link_name(json), pedigree_path(animal, @pedigree_click, @generations)
            - else
              = link_name(json)
            - if @annotation == :hip && hips(json)
              %font{color:"green"} [#{hips(json)}]
            - if @annotation == :longevity && longevity(animal)
              %font{color:"green"} [#{longevity(animal)}]
            - if generations > 1
              %td{style:"width:#{100*(1-1.0/generations)+5}%"}
                - ancestors = [animal.father, animal.mother]
                / = debug ancestors
                / = ancestors #{generations-1}
                = render partial:"tollerdata/pedigree/pedigree", locals:{animals:ancestors, |
                                                     generations:generations-1, |
                                                     link:true } |
    

app/views/tollerdata/pedigree/show.html.haml
- json = MultiJson.load @animal.import_json
- generations = @generations.to_words.capitalize
- title "#{generations} Generation Pedigree: #{link_name json}"
%p
  %strong
    %font{:size => "4"}
      - if !life_string(@animal).blank?
        #{link_name(json)}&nbsp;(#{life_string @animal})
      - else
        #{link_name(json)}

%p
  %font{:size => "3"}
    %strong #{generations} Generation Pedigree:
%font{:size => "1"}
  = render partial:"pedigree", locals:{animals:[@animal], generations:@generations+1, link:false}
%ul
  %li
    %font{:size => "2"}
      = link_to "Back to standard pedigree page", tollerdata_animal_path(@animal)
  - if @annotation
    %li
      %font{:size => "2"}
        = link_to "View stanard #{@generations}-generation pedigree", tollerdata_animal_pedigree_hip_path(@animal, @generations)
  - if @annotation != :hip
    %li
      %font{:size => "2"}
        = link_to "View #{@generations}-generation hip pedigree", tollerdata_animal_pedigree_hip_path(@animal, @generations)
  - if @annotation != :longevity
    %li
      %font{:size => "2"}
        = link_to "View #{@generations}-generation longevity pedigree", tollerdata_animal_pedigree_longevity_path(@animal, @generations)
%p
  = link_to "Return to home page", tollerdata_path
/ = debug json