config/routes.rb
Caninae::Application.routes.draw do
  resources :people
  resources :animal_kennels
  resources :animal_owners
  resources :succeeds
  resources :preceeds
  resources :dominates
  resources :titles
  resources :achievements
  resources :certifications
  resources :offspring_litters
  resources :litters
  resources :kennel_litters
  resources :person_kennels
  resources :kennels
  resources :registrations
  resources :animal_breeders
  resources :clearances
  resources :animals
  resources :events
  resources :locations

  namespace :tollerdata do
    get '/', :to => 'home#show'

    get :home, to:'home#show'
    get :about, to:'home#about'

    resources :animals do
      resources :siblings
      resources :offspring
      resources :pedigree do
        get :hip, to:'pedigree#hip'
        get :longevity, to:'pedigree#longevity'
      end
      resource :image
      resource :health do
        resources :categories, to:"health/categories"
      end
    end

    get :default, to:'home#show'
    resource :verify
  end
end

app/models/animal.rb
class Animal < ActiveRecord::Base
  belongs_to :mother, class_name:Animal
  belongs_to :father, class_name:Animal
  has_one :birth, as:"entity", class_name:Event, conditions:['event_type = ?', :birth]
  has_one :death, as:"entity", class_name:Event, conditions:['event_type = ?', :death]
  has_many :offspring
  has_many :events, as:"entity"
  has_many :registrations
  attr_accessible :address_id, :birth_id, :call_name, :death_id, :father_id
  attr_accessible :import_json, :litter_id, :mother_id, :name, :sex
end

app/models/tollerdata/animal.rb
class Tollerdata::Animal < ::Animal
  # attr_accessible :title, :body
end

app/controllers/animals_controller.rb
class AnimalsController < ApplicationController
  # GET /animals
  # GET /animals.json
  def index
    if params[:query]
      q = "%#{params[:query]}%"
      @animals =
        Animal.where("name like ? or call_name like ? collate nocase", q, q)
    else 
      @animals = Animal.limit(10)
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @animals }
    end
  end

  # GET /animals/1
  # GET /animals/1.json
  def show
    @animal = Animal.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @animal }
    end
  end

  # GET /animals/new
  # GET /animals/new.json
  def new
    @animal = Animal.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @animal }
    end
  end

  # GET /animals/1/edit
  def edit
    @animal = Animal.find(params[:id])
  end

  # POST /animals
  # POST /animals.json
  def create
    @animal = Animal.new(params[:animal])

    respond_to do |format|
      if @animal.save
        format.html { redirect_to @animal, notice: 'Animal was successfully created.' }
        format.json { render json: @animal, status: :created, location: @animal }
      else
        format.html { render action: "new" }
        format.json { render json: @animal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /animals/1
  # PUT /animals/1.json
  def update
    @animal = Animal.find(params[:id])

    respond_to do |format|
      if @animal.update_attributes(params[:animal])
        format.html { redirect_to @animal, notice: 'Animal was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @animal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /animals/1
  # DELETE /animals/1.json
  def destroy
    @animal = Animal.find(params[:id])
    @animal.destroy

    respond_to do |format|
      format.html { redirect_to animals_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/tollerdata/animals_controller.rb
class Tollerdata::AnimalsController < Tollerdata::TollerdataController
  def index
    if params[:query]
      q = "%#{params[:query]}%"
      @animals =
        Animal.where("name like ? or call_name like ? collate nocase", q, q)
    else 
      @animals = Animal.limit(10)
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @animals }
    end
  end

  def show
    @animal = Animal.find params[:id]
    @pedigree_click = :animal
    respond_to do |format|
      format.html
      format.json { render json:@animal }
    end
  end
end

app/helpers/animals_helper.rb
module AnimalsHelper
  def mother
    Animal.find_by_id @animal.mother_id
  end

  def father
    Animal.find_by_id @animal.father_id
  end
end

app/helpers/tollerdata/animals_helper.rb
module Tollerdata::AnimalsHelper

  def ofa
    false
  end

  def score condition, registry, value
    case [condition, registry.downcase]
    when [:hip, "ofa"]
      if m = value.match(/^DTR-\d+([EGF])\d+[MF]-(T|PI|VPI|NOPI)$/)
        case m[1]
        when 'E'; "Excellent"
        when 'G'; "Good"
        when 'F'; "Fair"
        end
      else
        "nope"
      end
    else; nil
    end
  end

  def image json
    image = json["IMAGE"]
    image.blank? ? nil : image
  end

  def image_user json
    user = clean(json["IMAGEUSER"])
    user.blank? ? nil : user
  end

  def web_site json
    web_site = json["WEBSITE"]
    web_site.blank? ? nil : web_site
  end

  def clean string
    string = string.squish if string
    string.blank? ? nil : string
  end

  COUNTRIES = {
    "US" => "United States",
    "FI" => "Finland",
    "CA" => "Canada"
  }

  def country_name code
    code.upcase! if code
    COUNTRIES[code] || code
  end

  def country json
    country_name(clean json["COUNTRY"])
  end
  
  def name jsona
    clean json["NAME"]
  end
  
  def link_name json
    clean [prefix(json), json["NAME"], suffix(json)].join(" ")
  end
  
  def prefix json
    clean json["FRONTTITLES"]
  end
  
  def suffix json
    clean json["ENDTITLES"]
  end
  
  def color json
    clean json["COLOR"]
  end
  
  def registry json
    clean json["REGISTRY"]
  end

  def registration_number json
    clean json["REGISTRATIONNUMBER"]
  end
  
  def breeder json
    clean json["BREEDER"]
  end
  
  def owner json
    clean json["OWNER"]
  end
  
  def death_reason json
    clean json["DEATHREASON"]
  end

  def addl_death_reason json
    clean json["ADDLDEATHREASON"]
  end

  def pra_test json
    case clean(json["PRATEST"].downcase)
    when 'a'; "Clear"
    when 'b'; "Carrier"
    when 'c'; "Affected"
    end
  end

  def cea_test json
    case clean(json["CEATEST"].downcase)
    when 'a'; "Clear"
    when 'b'; "Carrier"
    when 'c'; "Affected"
    end
  end

  def combine json, a, b
    clean [clean(json[a]), clean(json[b])].compact.join(" ")
  end

  def hips json
    combine json, "HIPREGISTRY", "HIPID"
  end
  
  def eyes json
    combine json, "EYEREGISTRY", "EYEID"
  end
  
  def heart json
    combine json, "HEARTREGISTRY", "HEARTID"
  end
  
  def elbows json
    combine json, "ELBOWREGISTRY", "ELBOWID"
  end
  
  def thyroid json
    combine json, "THYROIDREGISTRY", "THYROIDID"
  end
  
  def longevity animal
    birth = animal.birth
    death = animal.death
    return nil if !death || !birth
    years = (death.to_epoch - birth.to_epoch)/(365*24*60.0*60.0)
    int = years.truncate
    years -= int
    if years > 2.0/3
      years = "#{int+1}"
    elsif years > 1.0/3
      years = "#{int}.5"
    else 
      years = int.to_s
    end
    "#{years} years"
  end

end

app/views/animals/_form.html.haml
= form_for @animal do |f|
  - if @animal.errors.any?
    #error_explanation
      %h2= "#{pluralize(@animal.errors.count, "error")} prohibited this animal from being saved:"
      %ul
        - @animal.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :call_name
    = f.text_field :call_name
  .field
    = f.label :mother_id
    = f.number_field :mother_id
  .field
    = f.label :father_id
    = f.number_field :father_id
  .field
    = f.label :sex
    = f.text_field :sex
  .field
    = f.label :litter_id
    = f.number_field :litter_id
  .field
    = f.label :address_id
    = f.number_field :address_id
  .field
    = f.label :birth_id
    = f.number_field :birth_id
  .field
    = f.label :death_id
    = f.number_field :death_id
  .field
    = f.label :import_json
    = f.text_field :import_json
  .actions
    = f.submit 'Save'

app/views/animals/edit.html.haml
%h1 Editing animal

= render 'form'

= link_to 'Show', @animal
\|
= link_to 'Back', animals_path

app/views/animals/index.html.haml
%h1 #{Breed}

%table
  %tr
    %th Name
    %th Mother
    %th Father
    %th Sex
    %th Birth
    %th Death
    %th
    %th
    %th

  - @animals.each do |animal|
    %tr
      %td
        = link_to display_name(animal), animal_path(animal)
      %td
        - if animal.mother
          = link_to display_name(animal.mother), animal_path(animal.mother)
      %td
        - if animal.father
          = link_to display_name(animal.father), animal_path(animal.father)
      %td= animal.sex
      %td= readable_date animal.birth
      %td= readable_date animal.death
      %td= link_to 'Show', animal
      %td= link_to 'Edit', edit_animal_path(animal)
      %td= link_to 'Destroy', animal, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Animal', new_animal_path

app/views/animals/new.html.haml
%h1 New animal

= render 'form'

= link_to 'Back', animals_path

app/views/animals/show.html.haml
%p#notice= notice

/ = debug(@animal)
/ = debug(@animal.birth)
/ = debug(@animal.death)

%p
  %b Name:
  = display_name @animal
  - if life_string @animal
    = "(#{life_string @animal})"
- if mother
  %p
    %b #{Mother}:
    = link_to display_name(mother), animal_path(mother)
    - if life_string mother
      = "(#{life_string mother})"
- if father
  %p
    %b  #{Father}:
    = link_to display_name(father), animal_path(father)
    - if life_string father
      = "(#{life_string father})"
%p
  %b Sex:
  = @animal.sex

- if !@animal.events.empty?
  %p
    %b Events:
    %ul
      = render @animal.events

/
  %p
    %b Litter:
    = @animal.litter_id
/
  %p
    %b Address:
    = @animal.address_id
/
  %p
    %b Import json:
    = @animal.import_json

= link_to 'Edit', edit_animal_path(@animal)
\|
= link_to 'Back', animals_path