config/routes.rb
Caninae::Application.routes.draw do
  resources :people
  resources :animal_kennels
  resources :animal_owners
  resources :succeeds
  resources :preceeds
  resources :dominates
  resources :titles
  resources :achievements
  resources :certifications
  resources :offspring_litters
  resources :litters
  resources :kennel_litters
  resources :person_kennels
  resources :kennels
  resources :registrations
  resources :animal_breeders
  resources :clearances
  resources :animals
  resources :events
  resources :locations

  namespace :tollerdata do
    get '/', :to => 'home#show'

    get :home, to:'home#show'
    get :about, to:'home#about'

    resources :animals do
      resources :siblings
      resources :offspring
      resources :pedigree do
        get :hip, to:'pedigree#hip'
        get :longevity, to:'pedigree#longevity'
      end
      resource :image
      resource :health do
        resources :categories, to:"health/categories"
      end
    end

    get :default, to:'home#show'
    resource :verify
  end
end

app/models/achievement.rb
class Achievement < ActiveRecord::Base
  attr_accessible :event_id, :title_id
end

app/models/animal.rb
class Animal < ActiveRecord::Base
  belongs_to :mother, class_name:Animal
  belongs_to :father, class_name:Animal
  has_one :birth, as:"entity", class_name:Event, conditions:['event_type = ?', :birth]
  has_one :death, as:"entity", class_name:Event, conditions:['event_type = ?', :death]
  has_many :offspring
  has_many :events, as:"entity"
  has_many :registrations
  attr_accessible :address_id, :birth_id, :call_name, :death_id, :father_id
  attr_accessible :import_json, :litter_id, :mother_id, :name, :sex
end

app/models/animal_kennel.rb
class AnimalKennel < ActiveRecord::Base
  attr_accessible :animal_id, :kennel_id
end

app/models/animal_owner.rb
class AnimalOwner < ActiveRecord::Base
  attr_accessible :animal_id, :owner_id
end

app/models/certification.rb
class Certification < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/models/clearance.rb
class Clearance < ActiveRecord::Base
  attr_accessible :animal_id
end

app/models/dominate.rb
class Dominate < ActiveRecord::Base
  attr_accessible :dominated_id, :dominator_id
end

app/models/event.rb
class Event < ActiveRecord::Base
  attr_accessible :date, :entity_id, :entity_type, :location_id, :time, :event_type, :year, :month, :day, :hour, :minute, :second, :timezone
  belongs_to :entity, polymorphic:true

  def to_epoch
    return nil if year.blank?
    Date.new(*([year, month || 6, day || 15].compact)).to_time.to_i
  end

end

app/models/kennel.rb
class Kennel < ActiveRecord::Base
  attr_accessible :address_id, :name
end

app/models/kennel_litter.rb
class KennelLitter < ActiveRecord::Base
  attr_accessible :kennel_id, :litter_id
end

app/models/litter.rb
class Litter < ActiveRecord::Base
  attr_accessible :event_id, :father_id, :mother_id, :name
end

app/models/location.rb
class Location < ActiveRecord::Base
  attr_accessible :city, :country, :latitude, :longitude, :resolution, :state, :street
end

app/models/offspring_litter.rb
class OffspringLitter < ActiveRecord::Base
  attr_accessible :litter_id, :offspring_id
end

app/models/person.rb
class Person < ActiveRecord::Base
  attr_accessible :address_id, :first_name, :last_name
end

app/models/person_kennel.rb
class PersonKennel < ActiveRecord::Base
  attr_accessible :kennel_id, :person_id
end

app/models/preceed.rb
class Preceed < ActiveRecord::Base
  attr_accessible :first, :second
end

app/models/registration.rb
class Registration < ActiveRecord::Base
  attr_accessible :animal_id, :date, :registration_number, :registry_id
end

app/models/succeed.rb
class Succeed < ActiveRecord::Base
  attr_accessible :first, :second
end

app/models/title.rb
class Title < ActiveRecord::Base
  attr_accessible :abbreviation, :name, :prefix, :registry_id
end

app/models/tollerdata.rb
module Tollerdata
  def self.table_name_prefix
    'tollerdata_'
  end
end

app/controllers/offspring_litters_controller.rb
class OffspringLittersController < ApplicationController
  # GET /offspring_litters
  # GET /offspring_litters.json
  def index
    @offspring_litters = OffspringLitter.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @offspring_litters }
    end
  end

  # GET /offspring_litters/1
  # GET /offspring_litters/1.json
  def show
    @offspring_litter = OffspringLitter.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @offspring_litter }
    end
  end

  # GET /offspring_litters/new
  # GET /offspring_litters/new.json
  def new
    @offspring_litter = OffspringLitter.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @offspring_litter }
    end
  end

  # GET /offspring_litters/1/edit
  def edit
    @offspring_litter = OffspringLitter.find(params[:id])
  end

  # POST /offspring_litters
  # POST /offspring_litters.json
  def create
    @offspring_litter = OffspringLitter.new(params[:offspring_litter])

    respond_to do |format|
      if @offspring_litter.save
        format.html { redirect_to @offspring_litter, notice: 'Offspring litter was successfully created.' }
        format.json { render json: @offspring_litter, status: :created, location: @offspring_litter }
      else
        format.html { render action: "new" }
        format.json { render json: @offspring_litter.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /offspring_litters/1
  # PUT /offspring_litters/1.json
  def update
    @offspring_litter = OffspringLitter.find(params[:id])

    respond_to do |format|
      if @offspring_litter.update_attributes(params[:offspring_litter])
        format.html { redirect_to @offspring_litter, notice: 'Offspring litter was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @offspring_litter.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /offspring_litters/1
  # DELETE /offspring_litters/1.json
  def destroy
    @offspring_litter = OffspringLitter.find(params[:id])
    @offspring_litter.destroy

    respond_to do |format|
      format.html { redirect_to offspring_litters_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/offspring_litters_helper.rb
module OffspringLittersHelper
end

app/views/offspring_litters/_form.html.haml
= form_for @offspring_litter do |f|
  - if @offspring_litter.errors.any?
    #error_explanation
      %h2= "#{pluralize(@offspring_litter.errors.count, "error")} prohibited this offspring_litter from being saved:"
      %ul
        - @offspring_litter.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :litter_id
    = f.number_field :litter_id
  .field
    = f.label :offspring_id
    = f.number_field :offspring_id
  .actions
    = f.submit 'Save'

app/views/offspring_litters/edit.html.haml
%h1 Editing offspring_litter

= render 'form'

= link_to 'Show', @offspring_litter
\|
= link_to 'Back', offspring_litters_path

app/views/offspring_litters/index.html.haml
%h1 Listing offspring_litters

%table
  %tr
    %th Litter
    %th Offspring
    %th
    %th
    %th

  - @offspring_litters.each do |offspring_litter|
    %tr
      %td= offspring_litter.litter_id
      %td= offspring_litter.offspring_id
      %td= link_to 'Show', offspring_litter
      %td= link_to 'Edit', edit_offspring_litter_path(offspring_litter)
      %td= link_to 'Destroy', offspring_litter, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Offspring litter', new_offspring_litter_path

app/views/offspring_litters/new.html.haml
%h1 New offspring_litter

= render 'form'

= link_to 'Back', offspring_litters_path

app/views/offspring_litters/show.html.haml
%p#notice= notice

%p
  %b Litter:
  = @offspring_litter.litter_id
%p
  %b Offspring:
  = @offspring_litter.offspring_id

= link_to 'Edit', edit_offspring_litter_path(@offspring_litter)
\|
= link_to 'Back', offspring_litters_path